Assignment05 dev (#70)
* added workflow and yaml

* added workflow and packer

* added yaml

* added yaml

* added yaml

* added yaml

* added yaml

* modified pipwline

* modified pipwline

* modified pipwline

* modified source image

* modified source image

* modified shell command

* modified shell command

* modified shell command

* modified shell command

* modified shell command

* modified shell command

* modified shell command

* modified shell command

* added users

* added code

* added extra pipeline

* updated pipeline

* added env in provisioner

* added env file and password secret

* added env file and password secret

* added code

* added users.csv

* added users.csv with sudo

* added users.csv with sudo

* modified var

* modified variables in packer

* added provisioner

* added 404

* added 400 in delete

* added readm.md

* modified packer

* modified packer

* added service

* added ls

* added path

* added path

* added path

* added sudo to mv to etc

* modified packer

* modified packer

* modified packer

* modified packer

* modified service

* modified service

* added user and group

* added paker var

* adderd pak var

* added code

* modified paker fmt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* added /opt

* Update README.md

* added

* added code

* added code

* added cloudwatch

* sdded meta

* added / at last

* added statsd

* pkr fmt

* pkr add

* pkr add

* agent

* agent

* added logger

* added logger in health

* added jteest

* added metadata

* added metadata

* Delete .DS_Store

* added code

* added one endpoint

* added user

* added error

* added console

* modified datatyoe

* added logging statements

* added comment

* added code

* added code

* added user and logger

* added user and logger

* added ta email

* added error codes

* Delete src/.DS_Store

* added error codes in delete

* added error codes in delete and sub

* added error codes in delete and sub

* added assignmentId

* added pipeline

* modified readme

* modified readme

* modified readme

* modified pipeline to get latest version

* added lt version trigger

* added lt version trigger

* added endpoint organized

* added endpoint organized root

* added readme

* added readme

* modified v2 for test

* modified v2 for test

* modified v1 for test

* modified v1 for test

* added v3

* added v2

* added v2

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -202,6 +202,9 @@ jobs:
                   if [[ "$REFRESH_STATUS" == "Failed" ]]; then
                     echo "Instance refresh failed. Workflow failed."
                     exit 1
+                  if [[ "$REFRESH_STATUS" == "Cancelled" ]]; then
+                    echo "Instance refresh failed. Workflow failed."
+                    exit 1
                   else
                     echo "Instance refresh completed successfully."
                   fi
